#### Lire un CSV et L'explorer

In [1]:
# J'importe le module pandas
import pandas as pd

# je définis mon dataframe
df = pd.read_csv('data/Adherent.csv')

In [2]:
# Forme du dataframe : nombre de lignes et de colonnes
df.shape

(15, 7)

In [3]:
# j'affiche de données de chacune de mes colonnes
df.dtypes

client_id             int64
nom                  object
age                   int64
ville                object
salaire             float64
statut               object
date_inscription     object
dtype: object

In [4]:
# 5 premiers lignes de mon dataframe
df.head(5)

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
2,3,Sophie Martin,45,Lyon,67000.0,actif,2021-11-20
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
4,5,Emma Leroy,52,Paris,78500.0,actif,2020-05-17

In [5]:
# Description des données contenues dans mon df
df.describe()

       client_id        age       salaire
count  15.000000  15.000000     13.000000
mean    8.000000  36.733333  55538.461538
std     4.472136  10.109873  17623.872941
min     1.000000  22.000000  28500.000000
25%     4.500000  29.500000  41200.000000
50%     8.000000  34.000000  53200.000000
75%    11.500000  43.000000  67000.000000
max    15.000000  57.000000  89000.000000

In [6]:
# J'affiche le nombre de cellules vides dans chacune de mes colonnes
df.isnull().sum()

client_id           0
nom                 0
age                 0
ville               2
salaire             2
statut              1
date_inscription    0
dtype: int64

### Filtrer des Lignes et des colonnes

In [8]:
# Filtrer les lignes
df_filtre = df[df['age'] > 30]

In [9]:
# Sélectionner des colonnes
df_cols = df[['nom', 'age', 'salaire']]

In [15]:
# Combiner les deux 
df_resultat = df.loc[df['salaire'] > 50000, ['nom', 'salaire']]

print(df_resultat)

               nom  salaire
0     Marie Dupont  52000.0
2    Sophie Martin  67000.0
4       Emma Leroy  78500.0
6    Camille Simon  55800.0
8       Léa Garcia  61000.0
10     Julie David  89000.0
12  Clara Fontaine  53200.0
13    Pierre Morel  72100.0

In [24]:
# les lignes où age est entre 25 et 40.

df_25_40 = df[(df['age']>= 25 ) & (df['age']<= 40)]
df_25_40

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
5,6,Nathan Moreau,26,Bordeaux,NaN,actif,2023-06-22
6,7,Camille Simon,39,Lyon,55800.0,inactif,2021-08-30
7,8,Hugo Laurent,33,NaN,48300.0,actif,2022-12-11
9,10,Maxime Roux,29,Strasbourg,36900.0,actif,2023-09-14
12,13,Clara Fontaine,36,Nantes,53200.0,NaN,2022-04-19
14,15,Inès Girard,30,Lyon,NaN,actif,2023-11-03

In [26]:
# les lignes où age est entre 25 et 40 V2

df_25_40_V2 = df[df['age'].between(25, 40)]
df_25_40_V2

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
5,6,Nathan Moreau,26,Bordeaux,NaN,actif,2023-06-22
6,7,Camille Simon,39,Lyon,55800.0,inactif,2021-08-30
7,8,Hugo Laurent,33,NaN,48300.0,actif,2022-12-11
9,10,Maxime Roux,29,Strasbourg,36900.0,actif,2023-09-14
12,13,Clara Fontaine,36,Nantes,53200.0,NaN,2022-04-19
14,15,Inès Girard,30,Lyon,NaN,actif,2023-11-03

#### Groupby et agrégations

In [42]:
df_ventes = pd.read_csv('data/ventes.csv')

df_ventes.head(5)

      region         vendeur  ventes     mois
0      Paris    Marie Dupont    1200  Janvier
1       Lyon  Thomas Bernard     850  Janvier
2      Paris   Sophie Martin    2100  Janvier
3  Marseille     Lucas Petit     430  Janvier
4       Lyon      Emma Leroy    1750  Février

In [44]:
# Somme par groupe 
par_region = df_ventes.groupby('region')['ventes'].sum()
par_region

region
Lyon          5960
Marseille     2080
Paris        10810
Name: ventes, dtype: int64

In [46]:
# Plusieurs agrégations
stats = df_ventes.groupby('region').agg( 
    total_ventes =('ventes', 'sum'),
    moyenne    = ('ventes', 'mean'),
    nb_lignes  = ('ventes', 'count'),
    max_ventes = ('ventes', 'max')
    )

print(stats.reset_index())

      region  total_ventes      moyenne  nb_lignes  max_ventes
0       Lyon          5960  1192.000000          5        1750
1  Marseille          2080   520.000000          4         750
2      Paris         10810  1801.666667          6        3100

#### Merge / join entre deux tables

In [47]:
clients = pd.read_csv('data/clients.csv')
commandes = pd.read_csv('data/commandes.csv')

In [48]:
# Inner join
df_inner = pd.merge(clients, commandes, on='client_id', how='inner')
df_inner

,client_id,nom,ville,age,commande_id,produit,montant,date
0,1,Marie Dupont,Paris,34,101,Laptop,1200,2024-01-15
1,1,Marie Dupont,Paris,34,103,Clavier,85,2024-02-03
2,1,Marie Dupont,Paris,34,110,Webcam,75,2024-04-02
3,2,Thomas Bernard,Lyon,28,102,Souris,25,2024-01-18
4,2,Thomas Bernard,Lyon,28,106,Webcam,75,2024-03-01
5,3,Sophie Martin,Marseille,45,104,Écran,450,2024-02-10
6,4,Lucas Petit,Bordeaux,31,108,Souris,25,2024-03-12
7,5,Emma Leroy,Paris,52,105,Laptop,1200,2024-02-14

In [49]:
# Lest join
df_left = pd.merge(clients, commandes, on='client_id', how='left')
df_left

,client_id,nom,ville,age,commande_id,produit,montant,date
0,1,Marie Dupont,Paris,34,101.0,Laptop,1200.0,2024-01-15
1,1,Marie Dupont,Paris,34,103.0,Clavier,85.0,2024-02-03
2,1,Marie Dupont,Paris,34,110.0,Webcam,75.0,2024-04-02
3,2,Thomas Bernard,Lyon,28,102.0,Souris,25.0,2024-01-18
4,2,Thomas Bernard,Lyon,28,106.0,Webcam,75.0,2024-03-01
5,3,Sophie Martin,Marseille,45,104.0,Écran,450.0,2024-02-10
6,4,Lucas Petit,Bordeaux,31,108.0,Souris,25.0,2024-03-12
7,5,Emma Leroy,Paris,52,105.0,Laptop,1200.0,2024-02-14
8,6,Nathan Moreau,Nantes,26,NaN,NaN,NaN,NaN
9,7,Camille Simon,Lyon,39,NaN,NaN,NaN,NaN

In [50]:
# Vérification des lignes non matchées
non_matches = df_left[df_left['commande_id'].isnull()]
non_matches

   client_id            nom   ville  age  commande_id produit  montant date
8          6  Nathan Moreau  Nantes   26          NaN     NaN      NaN  NaN
9          7  Camille Simon    Lyon   39          NaN     NaN      NaN  NaN

In [51]:
df_right = pd.merge(clients, commandes, on='client_id', how='right')
df_right

,client_id,nom,ville,age,commande_id,produit,montant,date
0,1,Marie Dupont,Paris,34.0,101,Laptop,1200,2024-01-15
1,2,Thomas Bernard,Lyon,28.0,102,Souris,25,2024-01-18
2,1,Marie Dupont,Paris,34.0,103,Clavier,85,2024-02-03
3,3,Sophie Martin,Marseille,45.0,104,Écran,450,2024-02-10
4,5,Emma Leroy,Paris,52.0,105,Laptop,1200,2024-02-14
5,2,Thomas Bernard,Lyon,28.0,106,Webcam,75,2024-03-01
6,8,NaN,NaN,NaN,107,Casque,120,2024-03-05
7,4,Lucas Petit,Bordeaux,31.0,108,Souris,25,2024-03-12
8,9,NaN,NaN,NaN,109,Clavier,85,2024-03-20
9,1,Marie Dupont,Paris,34.0,110,Webcam,75,2024-04-02

#### Nettoyer des données (valeurs nulles)

In [65]:
df_data = pd.read_csv('data/data.csv')

In [66]:
# Voir les nulls
df_data.isnull().sum()

client_id           0
nom                 3
age                 4
ville               5
salaire             5
statut              3
date_inscription    2
dtype: int64

In [67]:
# Supprimer les lignes avec trop de nulls
df_data = df_data.dropna(thresh=5)

In [72]:
# Remplir les nulls numériques par la médiane
df_data['age']= df_data['age'].fillna(df_data['age'].median())
df_data['salaire']= df_data['salaire'].fillna(df_data['salaire'].mean())

In [73]:
# Remplir les nulls texte par 'Inconnu'
df_data['ville']= df_data['ville'].fillna('Inconnu')
df_data['statut']= df_data['statut'].fillna('Inconnu')

In [74]:
# Vérification
df_data.isnull().sum()

client_id           0
nom                 0
age                 0
ville               0
salaire             0
statut              0
date_inscription    0
dtype: int64

In [75]:
df_data

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34.0,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,35.0,Lyon,38500.0,actif,2023-01-08
3,4,Lucas Petit,31.0,Marseille,41200.0,inactif,2022-07-03
4,5,Emma Leroy,52.0,Paris,53020.0,actif,2020-05-17
5,6,Nathan Moreau,26.0,Inconnu,38000.0,actif,2023-06-22
7,8,Hugo Laurent,33.0,Inconnu,48300.0,actif,2022-12-11
8,9,Léa Garcia,41.0,Nantes,61000.0,actif,2021-03-04
9,10,Maxime Roux,35.0,Strasbourg,36900.0,Inconnu,2023-09-14
10,11,Julie David,57.0,Paris,89000.0,actif,2019-10-28
12,13,Clara Fontaine,36.0,Nantes,53200.0,Inconnu,2022-04-19
13,14,Pierre Morel,48.0,Marseille,72100.0,actif,2020-08-07
14,15,Inès Girard,30.0,Lyon,53020.0,actif,2023-11-03

#### Création et transformation des colonnes

In [77]:
df_ventes_v2 = pd.read_csv('data/ventes_v2.csv')

In [78]:
# Nouvelle colonne calculée
df_ventes_v2['marge'] = df_ventes_v2['prix'] - df_ventes_v2['cout']

In [79]:
# Colonne conditionnelle 
df_ventes_v2['categorie']= df_ventes_v2['marge'].apply(
    lambda x: 'bon' if x > 100 else ('moyen' if x >= 50 else 'faible')
)

In [80]:
# Transformation de texte
df_ventes_v2['region']= df_ventes_v2['region'].str.upper().str.strip()

In [81]:
# Convertir un type
df_ventes_v2['date'] = pd.to_datetime(df_ventes_v2['date'])

In [82]:
df_ventes_v2.head()

          vendeur     region  prix  cout       date  quantite  marge categorie
0    Marie Dupont      PARIS  1500  1200 2024-01-15         3    300       bon
1  Thomas Bernard       LYON   800   600 2024-01-18         5    200       bon
2   Sophie Martin  MARSEILLE  2200  1800 2024-02-03         2    400       bon
3     Lucas Petit      PARIS   950   820 2024-02-10         4    130       bon
4      Emma Leroy      PARIS  3100  2400 2024-02-14         1    700       bon

#### Sauvegarder et exporter des données

In [88]:
df_data = pd.read_csv('data/data.csv')

In [89]:
# Nettoyage minimal
df_data = df_data.dropna()
df_data.columns = [c.lower().strip() for c in df_data.columns]

In [94]:
# Export CSV
df_data.to_csv('data/export/data_propre.csv', index=False)

# Export Excel
df_data.to_excel('data/export/data_propre.xlsx', index=False, sheet_name='Data')

# Export partiel (filtre avant export)
df_data[df_data['statut'] == 'actif'].to_csv('data/export/actif.csv', index=False)

#Export JSON
df_data.to_json('data/export/data_propre.json', orient='records', indent=2)
print("Exports terminés")

Exports terminés