#### Lire un CSV et L'explorer

In [1]:
# J'importe le module pandas
import pandas as pd

# je définis mon dataframe
df = pd.read_csv('data/Adherent.csv')

In [2]:
# Forme du dataframe : nombre de lignes et de colonnes
df.shape

(15, 7)

In [3]:
# j'affiche de données de chacune de mes colonnes
df.dtypes

client_id             int64
nom                  object
age                   int64
ville                object
salaire             float64
statut               object
date_inscription     object
dtype: object

In [4]:
# 5 premiers lignes de mon dataframe
df.head(5)

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
2,3,Sophie Martin,45,Lyon,67000.0,actif,2021-11-20
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
4,5,Emma Leroy,52,Paris,78500.0,actif,2020-05-17

In [5]:
# Description des données contenues dans mon df
df.describe()

       client_id        age       salaire
count  15.000000  15.000000     13.000000
mean    8.000000  36.733333  55538.461538
std     4.472136  10.109873  17623.872941
min     1.000000  22.000000  28500.000000
25%     4.500000  29.500000  41200.000000
50%     8.000000  34.000000  53200.000000
75%    11.500000  43.000000  67000.000000
max    15.000000  57.000000  89000.000000

In [6]:
# J'affiche le nombre de cellules vides dans chacune de mes colonnes
df.isnull().sum()

client_id           0
nom                 0
age                 0
ville               2
salaire             2
statut              1
date_inscription    0
dtype: int64

### Filtrer des Lignes et des colonnes

In [8]:
# Filtrer les lignes
df_filtre = df[df['age'] > 30]

In [9]:
# Sélectionner des colonnes
df_cols = df[['nom', 'age', 'salaire']]

In [15]:
# Combiner les deux 
df_resultat = df.loc[df['salaire'] > 50000, ['nom', 'salaire']]

print(df_resultat)

               nom  salaire
0     Marie Dupont  52000.0
2    Sophie Martin  67000.0
4       Emma Leroy  78500.0
6    Camille Simon  55800.0
8       Léa Garcia  61000.0
10     Julie David  89000.0
12  Clara Fontaine  53200.0
13    Pierre Morel  72100.0

In [24]:
# les lignes où age est entre 25 et 40.

df_25_40 = df[(df['age']>= 25 ) & (df['age']<= 40)]
df_25_40

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
5,6,Nathan Moreau,26,Bordeaux,NaN,actif,2023-06-22
6,7,Camille Simon,39,Lyon,55800.0,inactif,2021-08-30
7,8,Hugo Laurent,33,NaN,48300.0,actif,2022-12-11
9,10,Maxime Roux,29,Strasbourg,36900.0,actif,2023-09-14
12,13,Clara Fontaine,36,Nantes,53200.0,NaN,2022-04-19
14,15,Inès Girard,30,Lyon,NaN,actif,2023-11-03

In [26]:
# les lignes où age est entre 25 et 40 V2

df_25_40_V2 = df[df['age'].between(25, 40)]
df_25_40_V2

,client_id,nom,age,ville,salaire,statut,date_inscription
0,1,Marie Dupont,34,Paris,52000.0,actif,2022-03-15
1,2,Thomas Bernard,28,NaN,38500.0,actif,2023-01-08
3,4,Lucas Petit,31,Marseille,41200.0,inactif,2022-07-03
5,6,Nathan Moreau,26,Bordeaux,NaN,actif,2023-06-22
6,7,Camille Simon,39,Lyon,55800.0,inactif,2021-08-30
7,8,Hugo Laurent,33,NaN,48300.0,actif,2022-12-11
9,10,Maxime Roux,29,Strasbourg,36900.0,actif,2023-09-14
12,13,Clara Fontaine,36,Nantes,53200.0,NaN,2022-04-19
14,15,Inès Girard,30,Lyon,NaN,actif,2023-11-03

#### Groupby et agrégations

In [42]:
df_ventes = pd.read_csv('data/ventes.csv')

df_ventes.head(5)

      region         vendeur  ventes     mois
0      Paris    Marie Dupont    1200  Janvier
1       Lyon  Thomas Bernard     850  Janvier
2      Paris   Sophie Martin    2100  Janvier
3  Marseille     Lucas Petit     430  Janvier
4       Lyon      Emma Leroy    1750  Février

In [44]:
# Somme par groupe 
par_region = df_ventes.groupby('region')['ventes'].sum()
par_region

region
Lyon          5960
Marseille     2080
Paris        10810
Name: ventes, dtype: int64

In [46]:
# Plusieurs agrégations
stats = df_ventes.groupby('region').agg( 
    total_ventes =('ventes', 'sum'),
    moyenne    = ('ventes', 'mean'),
    nb_lignes  = ('ventes', 'count'),
    max_ventes = ('ventes', 'max')
    )

print(stats.reset_index())

      region  total_ventes      moyenne  nb_lignes  max_ventes
0       Lyon          5960  1192.000000          5        1750
1  Marseille          2080   520.000000          4         750
2      Paris         10810  1801.666667          6        3100